### ISSUE TITLE
Exception handling doesn't catch SSL errors

### ISSUE THREAD

**Issue by mikekap** [abonas/kubeclient#201]
This causes the fluentd kubernetes plugin to bubble up an annoying exception right now:

```
2016-10-21T06:05:27.868171000Z 2016-10-21 06:05:27 +0000 [warn]: emit transaction failed: error_class=OpenSSL::SSL::SSLError error="SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A" tag="kubernetes.journal.container"
2016-10-21T06:05:27.868350000Z   2016-10-21 06:05:27 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
2016-10-21T06:05:27.868483000Z   2016-10-21 06:05:27 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http.rb:933:in `connect'
2016-10-21T06:05:27.868609000Z   2016-10-21 06:05:27 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
2016-10-21T06:05:27.868737000Z   2016-10-21 06:05:27 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
2016-10-21T06:05:27.868865000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb:766:in `transmit'
2016-10-21T06:05:27.868992000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb:215:in `execute'
2016-10-21T06:05:27.869121000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/rest-client-2.0.0/lib/restclient/request.rb:52:in `execute'
2016-10-21T06:05:27.869241000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/rest-client-2.0.0/lib/restclient/resource.rb:51:in `get'
2016-10-21T06:05:27.869369000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/kubeclient-1.1.4/lib/kubeclient/common.rb:204:in `block in get_entity'
2016-10-21T06:05:27.869508000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/kubeclient-1.1.4/lib/kubeclient/common.rb:58:in `handle_exception'
2016-10-21T06:05:27.869637000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/kubeclient-1.1.4/lib/kubeclient/common.rb:202:in `get_entity'
2016-10-21T06:05:27.869766000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/kubeclient-1.1.4/lib/kubeclient/common.rb:103:in `block (2 levels) in define_entity_methods'
2016-10-21T06:05:27.869890000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-0.25.3/lib/fluent/plugin/filter_kubernetes_metadata.rb:76:in `get_metadata'
2016-10-21T06:05:27.870018000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-0.25.3/lib/fluent/plugin/filter_kubernetes_metadata.rb:283:in `block (3 levels) in filter_stream_from_journal'
2016-10-21T06:05:27.870143000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/lru_redux-1.1.0/lib/lru_redux/ttl/cache.rb:52:in `getset'
2016-10-21T06:05:27.870268000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/lru_redux-1.1.0/lib/lru_redux/util/safe_sync.rb:26:in `block in getset'
2016-10-21T06:05:27.870392000Z   2016-10-21 06:05:27 +0000 [warn]: /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
2016-10-21T06:05:27.870517000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/lru_redux-1.1.0/lib/lru_redux/util/safe_sync.rb:25:in `getset'
2016-10-21T06:05:27.870681000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-0.25.3/lib/fluent/plugin/filter_kubernetes_metadata.rb:281:in `block (2 levels) in filter_stream_from_journal'
2016-10-21T06:05:27.870807000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-0.25.3/lib/fluent/plugin/filter_kubernetes_metadata.rb:266:in `match'
2016-10-21T06:05:27.870932000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-0.25.3/lib/fluent/plugin/filter_kubernetes_metadata.rb:266:in `block in filter_stream_from_journal'
2016-10-21T06:05:27.871063000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/event.rb:56:in `each'
2016-10-21T06:05:27.871191000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-0.25.3/lib/fluent/plugin/filter_kubernetes_metadata.rb:261:in `filter_stream_from_journal'
2016-10-21T06:05:27.871322000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/event_router.rb:152:in `block in emit'
2016-10-21T06:05:27.871446000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/event_router.rb:151:in `each'
2016-10-21T06:05:27.871570000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/event_router.rb:151:in `emit'
2016-10-21T06:05:27.871690000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/event_router.rb:90:in `emit_stream'
2016-10-21T06:05:27.871820000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/event_router.rb:81:in `emit'
2016-10-21T06:05:27.871946000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-rewrite-tag-filter-1.5.5/lib/fluent/plugin/out_rewrite_tag_filter.rb:75:in `block in emit'
2016-10-21T06:05:27.872070000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/event.rb:56:in `each'
2016-10-21T06:05:27.872193000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-rewrite-tag-filter-1.5.5/lib/fluent/plugin/out_rewrite_tag_filter.rb:72:in `emit'
2016-10-21T06:05:27.872319000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/event_router.rb:90:in `emit_stream'
2016-10-21T06:05:27.877453000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/event_router.rb:81:in `emit'
2016-10-21T06:05:27.877594000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-systemd-0.0.4/lib/fluent/plugin/in_systemd.rb:58:in `block in run'
2016-10-21T06:05:27.877727000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-systemd-0.0.4/lib/fluent/plugin/in_systemd.rb:71:in `watch'
2016-10-21T06:05:27.877855000Z   2016-10-21 06:05:27 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-systemd-0.0.4/lib/fluent/plugin/in_systemd.rb:57:in `run'

```

**Comment by simon3z** [comment]
cc @moolitayer

**Comment by cben** [comment]
Looks same as #240.
We wrap it IFF RestClient wrapped it, which depends on `error.message.include?("certificate verify failed")`.
I propose closing this in favor of #240 which has more details.

**Comment by moolitayer** [comment]
I affraied I missed this one back in Oct

**Comment by simon3z** [comment]
As mentioned in a [previous comment](https://github.com/abonas/kubeclient/issues/201#issuecomment-289691846) let's track this in #240
