### ISSUE TITLE
HTTP library is out of date and causuing error when used with Ruby >= 2.3.0 due to missing dependency 

### ISSUE THREAD

**Issue by gabe-ochoa** [abonas/kubeclient#220]
The HTTP library used in `kubeclient` is currently set at >= 0.9.8
https://github.com/abonas/kubeclient/blob/master/kubeclient.gemspec#L30

The most recent version is 2.1.0
https://github.com/httprb/http/releases

The HTTP library currently is causing errors when I use `kubeclient` with a project using the newest minor version of Ruby. 

```
LoadError: libruby.so.2.3: cannot open shared object file: No such file or directory - /home/ubuntu/job-scheduler/vendor/bundle/ruby/2.3.0/gems/http_parser.rb-0.6.0/lib/ruby_http_parser.so
  /home/ubuntu/job-scheduler/vendor/bundle/ruby/2.3.0/gems/http_parser.rb-0.6.0/lib/http_parser.rb:2:in `require'
  /home/ubuntu/job-scheduler/vendor/bundle/ruby/2.3.0/gems/http_parser.rb-0.6.0/lib/http_parser.rb:2:in `<top (required)>'
  /home/ubuntu/job-scheduler/vendor/bundle/ruby/2.3.0/gems/http_parser.rb-0.6.0/lib/http/parser.rb:1:in `require'
  /home/ubuntu/job-scheduler/vendor/bundle/ruby/2.3.0/gems/http_parser.rb-0.6.0/lib/http/parser.rb:1:in `<top (required)>'
  /home/ubuntu/job-scheduler/vendor/bundle/ruby/2.3.0/gems/http-0.9.8/lib/http.rb:1:in `require'
  /home/ubuntu/job-scheduler/vendor/bundle/ruby/2.3.0/gems/http-0.9.8/lib/http.rb:1:in `<top (required)>'
  /home/ubuntu/job-scheduler/vendor/bundle/ruby/2.3.0/gems/kubeclient-2.3.0/lib/kubeclient/watch_stream.rb:2:in `require'
  /home/ubuntu/job-scheduler/vendor/bundle/ruby/2.3.0/gems/kubeclient-2.3.0/lib/kubeclient/watch_stream.rb:2:in `<top (required)>'
  /home/ubuntu/job-scheduler/vendor/bundle/ruby/2.3.0/gems/kubeclient-2.3.0/lib/kubeclient.rb:7:in `require'
  /home/ubuntu/job-scheduler/vendor/bundle/ruby/2.3.0/gems/kubeclient-2.3.0/lib/kubeclient.rb:7:in `<top (required)>'
```

I have a forked branch with HTTP updated that has green tests but wanted to make an issue and see if there was a reason HTTP was set to an older version prior to making a PR to update it. 

Thanks!
~ Gabe

**Comment by simon3z** [comment]
Hi @gabe-ochoa we're discussing the gem updates in issue #206
I am closing this so that we can continue in a single issue (#206).
