### ISSUE TITLE
Upgrade webmock for ruby 2.4+ support

### ISSUE THREAD

**Issue by jrafanie** [abonas/kubeclient#242]
The existing kubeclient tests fail on ruby 2.4.1 because of a change described here (fixed in webmock 2.3.1):
https://github.com/ManageIQ/manageiq/pull/13104/commits/cb5adc5ddaf68ea6a503452ace70fa841a7b4892

That commit just monkey patches webmock but we should upgrade to the fixed webmock if we can.

The errors look like:
```
 31) Error:
KubeClientTest#test_api_valid_with_unreported_versions:
NoMethodError: undefined method `close' for #<StubSocket:0x007f85497095d8>
Did you mean?  closed?
               clone
    /Users/joerafaniello/.rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:981:in `do_finish'
    /Users/joerafaniello/.gem/ruby/2.4.1/gems/webmock-1.24.6/lib/webmock/http_lib_adapters/net_http.rb:125:in `start_without_connect'
    /Users/joerafaniello/.gem/ruby/2.4.1/gems/webmock-1.24.6/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
    /Users/joerafaniello/.gem/ruby/2.4.1/gems/rest-client-2.0.1/lib/restclient/request.rb:715:in `transmit'
    /Users/joerafaniello/.gem/ruby/2.4.1/gems/rest-client-2.0.1/lib/restclient/request.rb:145:in `execute'
    /Users/joerafaniello/.gem/ruby/2.4.1/gems/rest-client-2.0.1/lib/restclient/request.rb:52:in `execute'
    /Users/joerafaniello/.gem/ruby/2.4.1/gems/rest-client-2.0.1/lib/restclient/resource.rb:51:in `get'
    /Users/joerafaniello/Code/kubeclient/lib/kubeclient/common.rb:415:in `block in api'
    /Users/joerafaniello/Code/kubeclient/lib/kubeclient/common.rb:99:in `handle_exception'
    /Users/joerafaniello/Code/kubeclient/lib/kubeclient/common.rb:415:in `api'
    /Users/joerafaniello/Code/kubeclient/lib/kubeclient/common.rb:408:in `api_valid?'
    /Users/joerafaniello/Code/kubeclient/test/test_kubeclient.rb:132:in `test_api_valid_with_unreported_versions'
```

After allowing for webmock >= 2.3.1, 

```diff
diff --git a/kubeclient.gemspec b/kubeclient.gemspec
index b0e2366..889f609 100644
--- a/kubeclient.gemspec
+++ b/kubeclient.gemspec
@@ -22,7 +22,7 @@ Gem::Specification.new do |spec|
   spec.add_development_dependency 'bundler', '~> 1.6'
   spec.add_development_dependency 'rake', '~> 10.0'
   spec.add_development_dependency 'minitest'
-  spec.add_development_dependency 'webmock', '~> 1.24.2'
+  spec.add_development_dependency 'webmock', '~> 2.3.1'
   spec.add_development_dependency 'vcr'
   spec.add_development_dependency 'rubocop', '= 0.46.0'
   spec.add_dependency 'rest-client'
```

the VCR cassettes need to re-recorded.  I'm not sure how to generate the cassettes to re-record them with webmock 2.3.1+.

**Comment by simon3z** [comment]
cc @moolitayer @cben
