### ISSUE TITLE
How to list ingresses

### ISSUE THREAD

**Issue by Stono** [abonas/kubeclient#350]
Hey, 
I'm struggling to list ingresses.
My client currently looks like this:
```
        Kubeclient::Client.new(
          url + '/apis/extensions',
          'v1beta1',
          auth_options: auth_options,
          ssl_options: {
            verify_ssl: OpenSSL::SSL::VERIFY_NONE
          }
        )
```

But when starting up I get this:
```
Traceback (most recent call last):
        2: from lib/kubitzer.rb:10:in `<main>'
        1: from /usr/local/lib/ruby/gems/2.5.0/gems/kubeclient-4.0.0/lib/kubeclient/common.rb:90:in `method_missing'
/usr/local/lib/ruby/gems/2.5.0/gems/kubeclient-4.0.0/lib/kubeclient/common.rb:179:in `block (2 levels) in define_entity_methods': wrong number of arguments (given 0, expected 1..3) (ArgumentError)
```

Any ideas?

**Comment by Stono** [comment]
Never mind, should have been `ingresses`

**Comment by cben** [comment]
BTW, extensions v1beta1 is deprecated:
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ lists new API groups that replace it, with version rangeswhen you can/must switch.
