### ISSUE TITLE
create_security_context_constraint doesn't work

### ISSUE THREAD

**Issue by cben** [abonas/kubeclient#367]
This results from same mess as #307 but distinct problem.  We had a workaround for this for `create_endpoint` but `create_security_context_constraint` is broken.   It's an openshift resource, available both in 'v1' core api and a separate api group, neither works:
```
testing_scc = Kubeclient::Resource.new(
  metadata: {
    name: 'teleportation'
  },
  runAsUser: {
    type: 'MustRunAs'
  },
  seLinuxContext: {
    type: 'MustRunAs'
  }
)      

client = Kubeclient::Client.new(context.api_endpoint, context.api_version, ssl_options: context.ssl_options, auth_options: context.auth_options)

pry(main)> client = Kubeclient::Client.new(context.api_endpoint, 'v1', ssl_options: context.ssl_options, auth_options: context.auth_options)
pry(main)> client.create_security_context_constraint(testing_scc)
Kubeclient::HttpError: SecurityContextConstraint in version "v1" cannot be handled as a SecurityContextConstraints: no kind "SecurityContextConstraint" is registered for version "v1"
from /home/bpaskinc/kubeclient/lib/kubeclient/common.rb:125:in `rescue in handle_exception'
Caused by RestClient::BadRequest: 400 Bad Request
from /home/bpaskinc/myenv/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'

pry(main)> sclient = Kubeclient::Client.new(context.api_endpoint + '/apis/security.openshift.io', 'v1', ssl_options: context.ssl_options, auth_options: context.auth_options)
pry(main)> sclient.create_security_context_constraint(testing_scc)
Kubeclient::HttpError: SecurityContextConstraint in version "v1" cannot be handled as a SecurityContextConstraints: no kind "SecurityContextConstraint" is registered for version "security.openshift.io/v1"
from /home/bpaskinc/kubeclient/lib/kubeclient/common.rb:125:in `rescue in handle_exception'
Caused by RestClient::BadRequest: 400 Bad Request
from /home/bpaskinc/myenv/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
```

Fixing this (with tests) in #366.

**Comment by cben** [comment]
#261 is where SecurityContextConstraints was previously partially fixed.
